# Generated by Django 4.1.5 on 2023-01-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_book_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiikInstance',
            new_name='BookInstance',
        ),
    ]
